--COUNT
SELECT (319/29)+12 FROM DUAL;
SELECT 319/29+12 FROM DUAL;
SELECT 319 + 24 / 12 FROM DUAL;

-- CASE MANIPULATION FUNCTIONS (LOWER,UPPER,INITCAP)
SELECT * FROM PEGAWAI WHERE LOWER(NAMA_PEGAWAI)='bob';
SELECT * FROM PEGAWAI WHERE UPPER(NAMA_PEGAWAI)='RAHMA';
SELECT * FROM PEGAWAI WHERE INITCAP(NAMA_PEGAWAI)='James';
SELECT LOWER(NAMA_PEGAWAI) FROM PEGAWAI;
SELECT UPPER(NAMA_PEGAWAI) FROM PEGAWAI;
SELECT INITCAP(NAMA_PEGAWAI) FROM PEGAWAI;

--CHARACTER MANIPULATION FUNCTIONS
--MENGGABUNGKAN 2 NILAI SEPERTI CONCATENATION
SELECT CONCAT(NAMA_PEGAWAI,ALAMAT) FROM PEGAWAI;
SELECT CONCAT('Hello','World') FROM DUAL;
--EKSTRAK STRING SESUAI ANGKA YANG DITULISKAN 
SELECT SUBSTR(NAMA_PEGAWAI,1,3) FROM PEGAWAI;
SELECT SUBSTR(NAMA_PEGAWAI,4) FROM PEGAWAI;
SELECT SUBSTR('HelloWorld',6) FROM DUAL;
SELECT SUBSTR('HelloWorld',-5,3) FROM DUAL;
--MENAMPILKAN PANJANG STRING
SELECT LENGTH(NAMA_PEGAWAI) FROM PEGAWAI;
SELECT LENGTH('HelloWorld') FROM DUAL;
--KARAKTER ADA DI NOMOR BERAPA (YANG DITAMPILKAN YANG DI AWAL)
SELECT INSTR(NAMA_PEGAWAI,'A') FROM PEGAWAI;
SELECT INSTR('HELLOWORLD','W') FROM DUAL;
--MENGISI BAGIAN KIRI STRING DENGAN MENGGUNAKAN KARAKTER SEBANYAK KEKURANGANNYA
SELECT LPAD(NAMA_PEGAWAI,7,'*') FROM PEGAWAI;
SELECT LPAD(NAMA_PEGAWAI,5,'*') FROM PEGAWAI;
SELECT LPAD('HelloWorld',15,'-') FROM DUAL;
--MENGISI BAGIAN KANAN STRING DENGAN MENGGUNAKAN KARAKTER SEBANYAK KEKURANGANNYA
SELECT RPAD(NAMA_PEGAWAI,7,'*') FROM PEGAWAI;
SELECT RPAD(NAMA_PEGAWAI,5,'*') FROM PEGAWAI;
SELECT RPAD('HelloWorld',15,'-') FROM DUAL;
--MENGHAPUS LEADING(DEPAN), TRAILING(BELAKANG), BOTH(KEDUANYA)
SELECT TRIM(LEADING 'A' FROM 'ABCBA') FROM DUAL;
SELECT TRIM(LEADING 'S' FROM ID_SEWA) FROM DETAIL_SEWA;
SELECT TRIM(TRAILING 'A' FROM 'ABCBA') FROM DUAL;
SELECT TRIM(TRAILING '1' FROM ID_SEWA) FROM DETAIL_SEWA;
SELECT TRIM(BOTH 'A' FROM 'ABCBA') FROM DUAL;
SELECT TRIM(BOTH 'B' FROM NAMA_PEGAWAI) FROM PEGAWAI;
--MENGGANTI KARAKTER DALAM STRING DENGAN KARAKTER LAIN
SELECT REPLACE('JACK AND JUE','J','BL') FROM DUAL;
SELECT REPLACE('JACK AND JUE','J') FROM DUAL;
SELECT REPLACE(NAMA_PEGAWAI,'A','*') FROM PEGAWAI;

--USING COLUMN ALIASES WITH FUNCTIONS
SELECT LOWER(NAMA_PEGAWAI)||LOWER(SUBSTR(ALAMAT,1,2)) "User Name" FROM PEGAWAI;

--SUBSTITUTION VARIABELS (:)
SELECT * FROM PEGAWAI WHERE ID_PEGAWAI=:ENTER_ID_PEGAWAI;


--ROUND(BULAT KE ATAS),TRUNC (BULAT KE BAWAH), MOD
SELECT ROUND(456.98) FROM DUAL;
SELECT ROUND(456.985,2) FROM DUAL;
SELECT ROUND(456.985,-1) FROM DUAL;

SELECT TRUNC(456.98) FROM DUAL;
SELECT TRUNC(456.985,2) FROM DUAL;
SELECT TRUNC(456.985,-1) FROM DUAL;

SELECT MOD(456,5) FROM DUAL;


--SYSDATE
SELECT SYSDATE FROM DUAL;
SELECT ID_MOBIL,ID_SEWA, TGL_BAYAR +60 FROM DETAIL_SEWA;
SELECT ID_MOBIL,ID_SEWA, (SYSDATE-TGL_BAYAR)/7 FROM DETAIL_SEWA;
SELECT ID_MOBIL,ID_SEWA, (SYSDATE-TGL_BAYAR)/365 FROM DETAIL_SEWA;
SELECT ADD_MONTHS(SYSDATE,12) "NEXT YEAR" FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'SATURDAY') "NEXT SATURDAY" FROM DUAL;
SELECT LAST_DAY(SYSDATE) "END OF THE MONTH" FROM DUAL;

--ROUND MONTH YANG DILIHAT HARINYAA, ROUND YEAR DILIHAT BULANNYA
SELECT TGL_BAYAR, ROUND(TGL_BAYAR,'MONTH') FROM DETAIL_SEWA;
SELECT TGL_BAYAR, ROUND(TGL_BAYAR,'YEAR') FROM DETAIL_SEWA;
--
SELECT TGL_BAYAR, TRUNC(TGL_BAYAR,'MONTH') FROM DETAIL_SEWA;
SELECT TGL_BAYAR, TRUNC(TGL_BAYAR,'YEAR') FROM DETAIL_SEWA;

SELECT TRUNC(ROUND(456.98))
FROM dual;