CREATE TABLE PRODUK
(ID_PRODUK INT,
NAMA_PRODUK VARCHAR2(100),
JUMLAH NUMBER(5,0));

DESC PRODUK;

ALTER TABLE PRODUK
ADD(
HARGA NUMBER,
TANGGAL DATE DEFAULT SYSDATE
);

ALTER TABLE PRODUK
MODIFY (NAMA_PRODUK VARCHAR2(150));

ALTER TABLE PRODUK
ADD CONSTRAINT ID_PRODUK_PK PRIMARY KEY(ID_PRODUK); 

CREATE TABLE KATEGORI(
ID_KATEGORI NUMBER CONSTRAINT ID_KATEGORI_PK PRIMARY KEY,
NAMA_KATEGORI VARCHAR2(100)
);

ALTER TABLE PRODUK
ADD (
ID_KATEGORI NUMBER,
FOREIGN KEY (ID_KATEGORI) REFERENCES KATEGORI(ID_KATEGORI)
);



--TUGAS
--1
CREATE TABLE BARANG(
KODE_BARANG CHAR(6) PRIMARY KEY,
NAMA_BARANG VARCHAR2(20),
SATUAN_BARANG VARCHAR2(10)
);

DESC BARANG;

--2
ALTER TABLE BARANG
ADD STOK_BARANG NUMBER;

DESC BARANG;

--3
CREATE TABLE SUPLIER(
KODE_SUPLIER CHAR(6) PRIMARY KEY,
NAMA_SUPLIER VARCHAR2(30),
ALAMAT_SUPLIER VARCHAR2(50)
);

DESC SUPLIER;

--4
CREATE TABLE SUPLIER(
KODE_SUPLIER CHAR(6) PRIMARY KEY,
NAMA_SUPLIER VARCHAR2(30),
ALAMAT_SUPLIER VARCHAR2(50)
);

DESC SUPLIER;

--5
ALTER TABLE SUPLIER
MODIFY (ALAMAT_SUPLIER CHAR(40));

DESC SUPLIER;

--6
CREATE TABLE CUSTOMER(
KODE_COSTUMER CHAR(6) PRIMARY KEY,
NAMA_CUSTOMER VARCHAR2(30),
ALAMAT_CUSTOMER VARCHAR2(50)
);

DESC CUSTOMER;




