-- Tabel Penyedia Beasiswa
CREATE TABLE PENYEDIA_BEASISWA (
    ID_PENYEDIA VARCHAR2(10) PRIMARY KEY,
    NAMA_PENYEDIA VARCHAR2(50),
    WEBSITE_PENYEDIA VARCHAR2(100)
);

-- Tabel Negara
CREATE TABLE NEGARA (
    ID_NEGARA VARCHAR2(10) PRIMARY KEY,
    NAMA_NEGARA VARCHAR2(50),
    BAHASA VARCHAR2(50)
);

-- Tabel Perguruan Tinggi
CREATE TABLE PERGURUAN_TINGGI (
    ID_PERGURUAN_TINGGI VARCHAR2(10) PRIMARY KEY,
    ID_NEGARA VARCHAR2(10),
    NAMA_PERGURUAN_TINGGI VARCHAR2(50),
    WEBSITE_PERGURUAN_TINGGI VARCHAR2(100),
    CONSTRAINT FK_NEGARA
        FOREIGN KEY (ID_NEGARA)
        REFERENCES NEGARA (ID_NEGARA)
);

-- Tabel Jenjang
CREATE TABLE JENJANG (
    ID_JENJANG VARCHAR2(10) PRIMARY KEY,
    JENJANG_PENDIDIKAN VARCHAR2(10),
    LAMA_PENDIDIKAN NUMBER
);

-- Tabel Program Studi 
CREATE TABLE PROGRAM_STUDI (
    ID_PRODI VARCHAR2(10) PRIMARY KEY,
    NAMA_PRODI VARCHAR2(50)
);
    

-- Tabel Program Studi
CREATE TABLE DETAIL_PRODI (
    ID_DETAIL_PRODI VARCHAR2(10) PRIMARY KEY,
    ID_PRODI VARCHAR2(10),
    ID_JENJANG VARCHAR2(10),
    ID_PERGURUAN_TINGGI VARCHAR2(10),
    CONSTRAINT FK_PRODI
        FOREIGN KEY (ID_PRODI)
        REFERENCES PROGRAM_STUDI (ID_PRODI),
    CONSTRAINT FK_JENJANG
        FOREIGN KEY (ID_JENJANG)
        REFERENCES JENJANG (ID_JENJANG),
    CONSTRAINT FK_PT
        FOREIGN KEY (ID_PERGURUAN_TINGGI)
        REFERENCES PERGURUAN_TINGGI (ID_PERGURUAN_TINGGI)
);

-- Tabel Jenis Beasiswa
CREATE TABLE JENIS_BEASISWA(
    ID_BEASISWA VARCHAR2(10) PRIMARY KEY,
    ID_PENYEDIA VARCHAR2(10),
    NAMA_BEASISWA VARCHAR2(50),
    DESKRIPSI_BEASISWA VARCHAR2(1000),
    PERSYARATAN VARCHAR2(1000),
    BESARAN_DANA NUMBER,
    TANGGAL_MULAI DATE,
    TANGGAL_AKHIR DATE,
    CONSTRAINT BEASISWA_FK_PENYEDIA
        FOREIGN KEY (ID_PENYEDIA)
        REFERENCES PENYEDIA_BEASISWA (ID_PENYEDIA)
);

--Tabel Beasiswa dan Jenjang
CREATE TABLE BEASISWA_JENJANG(
    ID_BEA_JENJANG VARCHAR2(10) PRIMARY KEY,
    ID_BEASISWA VARCHAR2(10),
    ID_JENJANG VARCHAR2(10),
    CONSTRAINT FK_BEASISWA_JENJANG
        FOREIGN KEY (ID_BEASISWA)
        REFERENCES JENIS_BEASISWA (ID_BEASISWA),
    CONSTRAINT BEASISWA_FK_JENJANG
        FOREIGN KEY (ID_JENJANG)
        REFERENCES JENJANG (ID_JENJANG)
);

-- Tabel Beasiswa dan Negara
CREATE TABLE BEASISWA_NEGARA (
    ID_DETAIL_BEASISWA VARCHAR2(10) PRIMARY KEY,
    ID_BEASISWA VARCHAR2(10),
    ID_NEGARA VARCHAR2(10),
    CONSTRAINT FK_BEASISWA_NEGARA
        FOREIGN KEY (ID_BEASISWA)
        REFERENCES JENIS_BEASISWA (ID_BEASISWA),
    CONSTRAINT BEASISWA_FK_NEGARA
        FOREIGN KEY (ID_NEGARA)
        REFERENCES NEGARA (ID_NEGARA)
);
