--MELIHAT SEMUA BEASISWA DAN PENYEDIA BEASISWA pada tahun 2024
SELECT NAMA_BEASISWA, NAMA_PENYEDIA, DESKRIPSI_BEASISWA, PERSYARATAN, BESARAN_DANA, TANGGAL_MULAI, TANGGAL_AKHIR
FROM JENIS_BEASISWA JB JOIN PENYEDIA_BEASISWA PB ON (JB.ID_PENYEDIA = PB.ID_PENYEDIA) 
WHERE EXTRACT (YEAR FROM TANGGAL_MULAI) = 2024;

--MENGETAHUI BANYAKNYA BEASISWA DARI MASING-MASING NEGARA YANG DIURUTKAN DARI PALING BANYAK BEASISWA YANG ADA
SELECT NEG.NAMA_NEGARA, COUNT(ID_BEASISWA) "BANYAKNYA BEASISWA"
FROM BEASISWA_NEGARA BN JOIN NEGARA NEG ON (BN.ID_NEGARA = NEG.ID_NEGARA) 
GROUP BY(BN.ID_NEGARA, NAMA_NEGARA) 
ORDER BY "BANYAKNYA BEASISWA" DESC;

--BEASISWA UNTUK MAHASISWA D4
SELECT NAMA_BEASISWA, DESKRIPSI_BEASISWA, PERSYARATAN, BESARAN_DANA, TANGGAL_MULAI, TANGGAL_AKHIR
FROM JENIS_BEASISWA WHERE ID_BEASISWA IN 
(SELECT ID_BEASISWA FROM BEASISWA_JENJANG WHERE ID_JENJANG IN 
(SELECT ID_JENJANG FROM JENJANG WHERE JENJANG_PENDIDIKAN = 'D4'));

--BEASISWA LUAR NEGERI
SELECT ID_BEASISWA, NAMA_BEASISWA, DESKRIPSI_BEASISWA, PERSYARATAN, BESARAN_DANA, TANGGAL_MULAI, TANGGAL_AKHIR 
FROM JENIS_BEASISWA WHERE ID_BEASISWA IN
(SELECT ID_BEASISWA FROM BEASISWA_NEGARA WHERE ID_NEGARA IN 
(SELECT ID_NEGARA FROM NEGARA WHERE ID_NEGARA>'NG1'));

--BEASISWA DALAM NEGERI
SELECT NAMA_BEASISWA, DESKRIPSI_BEASISWA, PERSYARATAN, BESARAN_DANA, TANGGAL_MULAI, TANGGAL_AKHIR 
FROM JENIS_BEASISWA WHERE ID_BEASISWA IN
(SELECT ID_BEASISWA FROM BEASISWA_NEGARA WHERE ID_NEGARA IN 
(SELECT ID_NEGARA FROM NEGARA WHERE NAMA_NEGARA = 'Indonesia'));



