--Create View Beasiswa yang menampilkan beasiswa tersedia
CREATE VIEW BEASISWA AS SELECT NAMA_BEASISWA,NAMA_PENYEDIA,DESKRIPSI_BEASISWA,PERSYARATAN,BESARAN_DANA,TANGGAL_MULAI, TANGGAL_AKHIR 
FROM JENIS_BEASISWA JB JOIN PENYEDIA_BEASISWA PB ON (JB.ID_PENYEDIA = PB.ID_PENYEDIA);

SELECT * FROM BEASISWA;

--Create View Beasiswa yang ada di UGM 
CREATE VIEW BEASISWA_UGM AS SELECT JB.NAMA_BEASISWA,JB.DESKRIPSI_BEASISWA,JB.PERSYARATAN,JB.BESARAN_DANA,JB.TANGGAL_MULAI,JB.TANGGAL_AKHIR 
FROM JENIS_BEASISWA JB JOIN BEASISWA_NEGARA BN ON(JB.ID_BEASISWA=BN.ID_BEASISWA) JOIN NEGARA N ON(BN.ID_NEGARA=N.ID_NEGARA) JOIN PERGURUAN_TINGGI PT ON(N.ID_NEGARA=PT.ID_NEGARA)
WHERE PT.NAMA_PERGURUAN_TINGGI = 'Universitas Gadjah Mada';

SELECT * FROM BEASISWA_UGM;
