SELECT * FROM DETAIL_SEWA;

--COMPARISON OPERATORS
SELECT * FROM DETAIL_SEWA WHERE HARGA_TOTAL BETWEEN 105000 AND 800000;
SELECT * FROM DETAIL_SEWA WHERE HARGA_TOTAL IN 900000;
SELECT * FROM PEGAWAI WHERE NAMA_PEGAWAI LIKE '%A%';
SELECT * FROM PEGAWAI WHERE NAMA_PEGAWAI LIKE 'A%';
SELECT * FROM PEGAWAI WHERE NAMA_PEGAWAI LIKE '_A%';
SELECT * FROM PEGAWAI WHERE NAMA_PEGAWAI LIKE '%A';
SELECT * FROM PEGAWAI WHERE NAMA_PEGAWAI LIKE '%I_';
SELECT * FROM MOBIL WHERE TAHUN BETWEEN '01-01-2006' AND '01-01-2009';
SELECT * FROM MOBIL WHERE TAHUN BETWEEN TO_DATE('2006','YYYY') AND TO_DATE('2009','YYYY');
SELECT * FROM MOBIL WHERE ID_MOBIL IS NOT NULL;
SELECT * FROM MOBIL WHERE ID_MOBIL IS NULL;
select * from detail_sewa where harga_total like '%5%';

--LOGICAL COMPARISONS AND PRESEDENCE RULES
SELECT * FROM PEGAWAI WHERE ID_JABATAN LIKE 'SO%' AND ALAMAT NOT IN 'SURABAYA' OR ALAMAT IN('MALANG');
--AND LEBIH DULU DARIPADA OR


--SORTING ROWS
SELECT * FROM DETAIL_SEWA ORDER BY TGL_BAYAR;
SELECT * FROM PEGAWAI ORDER BY NAMA_PEGAWAI,ALAMAT;
SELECT * FROM DETAIL_SEWA ORDER BY TGL_BAYAR,HARGA_TOTAL DESC;
SELECT * FROM MOBIL WHERE MERK_MOBIL LIKE '%SUZUKI%' AND TAHUN BETWEEN '01-01-2005' AND '31-12-2007'ORDER BY TAHUN DESC;


-- TUGAS PERTEMUAN 3 PDB
SELECT * FROM DETAIL_SEWA WHERE HARGA_TOTAL BETWEEN 700000 AND 1000000;
SELECT * FROM MOBIL WHERE ID_MOBIL LIKE 'L%AZ' OR ID_MOBIL LIKE 'L%AS';
SELECT * FROM MOBIL WHERE TAHUN >= '01-01-2007' AND HARGA_SEWA > 300000;
SELECT * FROM PENYEWA WHERE NAMA_PENYEWA LIKE '%I' OR NAMA_PENYEWA LIKE '%E';
SELECT * FROM PEGAWAI WHERE ID_JABATAN = 'SO001' AND (ALAMAT = 'SURABAYA' OR ALAMAT='BANDUNG') ;
SELECT NAMA_PEGAWAI FROM PEGAWAI ORDER BY NAMA_PEGAWAI;
SELECT * FROM PENYEWAAN WHERE ID_PEGAWAI = 'PEG002' ORDER BY TGL_MULAI_SEWA DESC;
SELECT * FROM MOBIL WHERE MERK_MOBIL LIKE '%HONDA%' OR (MERK_MOBIL LIKE '%SUZUKI%' AND (TAHUN BETWEEN '01-01-2005' AND '31-12-2005' OR TAHUN BETWEEN '01-01-2010' AND '31-12-2010'));
