CREATE TABLE PEMAIN(
ID_PEMAIN VARCHAR2(5) NOT NULL PRIMARY KEY,
NAMA_PEMAIN VARCHAR2 (15),
ID_NEGARA VARCHAR2(5),
ID_CLUB VARCHAR2(5),
NO_PUNGGUNG INTEGER);

CREATE TABLE CLUB(
ID_CLUB VARCHAR2(5) NOT NULL PRIMARY KEY,
NAMA_CLUB VARCHAR2(20),
ID_NEGARA VARCHAR2(5));

CREATE TABLE NEGARA(
ID_NEGARA VARCHAR2(5) NOT NULL PRIMARY KEY,
NAMA_NEGARA VARCHAR2(10));

INSERT INTO NEGARA VALUES('NGR01','BRAZIL');
INSERT INTO NEGARA VALUES('NGR02','BELANDA');
INSERT INTO NEGARA VALUES('NGR03','INDONESIA');

UPDATE NEGARA SET NAMA_NEGARA = 'JERMAN' WHERE ID_NEGARA = 'NGR01';
DELETE FROM NEGARA WHERE ID_NEGARA='NGR01';
DELETE FROM NEGARA;

INSERT INTO negara VALUES('ngr01', 'Belanda');
INSERT INTO negara VALUES('ngr02', 'Indonesia');
INSERT INTO negara VALUES('ngr03', 'Brazil');
INSERT INTO negara VALUES('ngr04', 'Inggris');
INSERT INTO negara VALUES('ngr05', 'Spanyol');

INSERT INTO club VALUES('cb001', 'Ajax Amsterdam', 'ngr01');
INSERT INTO club VALUES('cb002', 'Real Madrid', 'ngr05');
INSERT INTO club VALUES('cb003', 'Manchester United', 'ngr04');

INSERT INTO pemain VALUES('ply01', 'Diego Costa', 'ngr05', 'cb001', '9');
INSERT INTO pemain VALUES('ply02', 'Sergio Ramos', 'ngr05', 'cb002', '4');

SELECT N.NAMA_NEGARA, COUNT(P.ID_PEMAIN) FROM NEGARA N LEFT OUTER JOIN PEMAIN P ON(N.ID_NEGARA = P.ID_NEGARA) GROUP BY NAMA_NEGARA;
SELECT P.NAMA_PEMAIN, NAMA_CLUB, N.NAMA_NEGARA, P.NO_PUNGGUNG FROM PEMAIN P INNER JOIN CLUB C ON (P.ID_CLUB=C.ID_CLUB) INNER JOIN NEGARA N ON (P.ID_NEGARA = N.ID_NEGARA);

DROP TABLE CLUB;
DROP TABLE NEGARA;
DROP TABLE PEMAIN;
