SELECT * 
FROM MOBIL M, DETAIL_SEWA DS, PENYEWAAN P 
WHERE M.ID_MOBIL = DS.ID_MOBIL AND P.ID_SEWA = DS.ID_SEWA;
 --DS.ID_SEWA, M.ID_MOBIL, M.MERK_MOBIL, P.TGL_MULAI_SEWA, P.TGL_AKHIR_SEWA--
 
SELECT *
FROM MOBIL NATURAL JOIN DETAIL_SEWA;
SELECT *
FROM MOBIL CROSS JOIN DETAIL_SEWA;
--ID_SEWA,ID_MOBIL,MERK_MOBIL,TGL_MULAI_SEWA,TGL_AKHIR_SEWA--

SELECT * FROM MOBIL JOIN DETAIL_SEWA USING (ID_MOBIL);
SELECT * FROM MOBIL M JOIN DETAIL_SEWA DS ON (M.ID_MOBIL = DS.ID_MOBIL);

SELECT * FROM MOBIL M LEFT OUTER JOIN DETAIL_SEWA DS USING (ID_MOBIL);

SELECT * FROM DETAIL_SEWA DS RIGHT OUTER JOIN MOBIL M USING (ID_MOBIL);

SELECT * FROM MOBIL M FULL OUTER JOIN DETAIL_SEWA DS USING (ID_MOBIL);

SELECT * FROM MOBIL M LEFT OUTER JOIN DETAIL_SEWA DS ON (M.ID_MOBIL = DS.ID_MOBIL);

SELECT * FROM DETAIL_SEWA DS RIGHT OUTER JOIN MOBIL M ON (M.ID_MOBIL = DS.ID_MOBIL);

SELECT * FROM MOBIL M FULL OUTER JOIN DETAIL_SEWA DS ON (M.ID_MOBIL = DS.ID_MOBIL);







--TUGAS
--1
SELECT LPAD(NAMA_PEGAWAI,10,'-')AS NAMA FROM PEGAWAI;

--2
SELECT CONCAT(SUBSTR(ID_JABATAN,1,2),SUBSTR(NAMA_PEGAWAI,1,3))AS "KODE SPESIFIK" FROM PEGAWAI;

--3
SELECT * FROM MOBIL WHERE (SYSDATE-TAHUN)/365>=15;

--4
SELECT ID_PEGAWAI,ID_JABATAN,NAMA_PEGAWAI,ALAMAT 
FROM PEGAWAI JOIN JABATAN USING(ID_JABATAN) WHERE NAMA_JABATAN = 'SOPIR';

--5
SELECT ID_SEWA,MERK_MOBIL,TGL_MULAI_SEWA,TGL_AKHIR_SEWA 
FROM MOBIL LEFT OUTER JOIN DETAIL_SEWA USING(ID_MOBIL) LEFT OUTER JOIN PENYEWAAN USING (ID_SEWA) 
WHERE MERK_MOBIL LIKE 'SUZUKI%';

--6
SELECT A.ID_PEGAWAI,A.ID_JABATAN,A.NAMA_PEGAWAI,A.ALAMAT 
FROM PEGAWAI A LEFT OUTER JOIN PENYEWAAN B ON(A.ID_PEGAWAI=B.ID_PEGAWAI)
WHERE B.ID_PEGAWAI IS NULL ;


