DROP VIEW BARANG_VIEW;
DROP VIEW DETIL_PEMBELIAN;
DROP VIEW DETIL_PEMBELIAN_READ_ONLY;
DROP TABLE KARYAWAN;


--1. a. Buatlah VIEW sederhana untuk data barang yang hanya berisi data kode barang,nama barang, dan satuan barang!
CREATE VIEW BARANG_VIEW AS SELECT KODE_BARANG, NAMA_BARANG, SATUAN_BARANG FROM BARANG;
--   b. Gunakan VIEW yang sudah dibuat untuk menampilkan data kode barang, nama, dan satuan!
SELECT * FROM BARANG_VIEW;

--2. a. Buatlah VIEW kompleks untuk mempermudah akses terhadap informasi yang sering diakses!
CREATE VIEW DETIL_PEMBELIAN AS
SELECT B.KODE_BARANG, B.NAMA_BARANG, B.STOK_BARANG, SUM(P.JUMLAH_PEMBELIAN)"JUMLAH_PEMBELIAN"
FROM BARANG B
LEFT OUTER JOIN PEMBELIAN P ON (B.KODE_BARANG = P.KODE_BARANG)
GROUP BY B.KODE_BARANG, B.NAMA_BARANG, B.STOK_BARANG;
--   b. Gunakan VIEW yang telah dibuat untuk menampilkan 2 informasi yang berbeda!
SELECT * FROM DETIL_PEMBELIAN;
SELECT * FROM DETIL_PEMBELIAN WHERE JUMLAH_PEMBELIAN > 10;
SELECT * FROM DETIL_PEMBELIAN WHERE UPPER(NAMA_BARANG) = 'RADIO';

--3. a. Ubah VIEW dengan menambahkan batasan sehingga data pada view hanya dapat dilihat dan tidak dapat diubah atau dihapus!
CREATE OR REPLACE VIEW DETIL_PEMBELIAN_READ_ONLY AS
SELECT KODE_BARANG, NAMA_BARANG, STOK_BARANG, JUMLAH_PEMBELIAN
FROM DETIL_PEMBELIAN
WITH READ ONLY;
--   b. Tunjukkan bahwa batasan yang diberikan berhasil!
INSERT INTO DETIL_PEMBELIAN_READ_ONLY (KODE_BARANG, NAMA_BARANG, STOK_BARANG, JUMLAH_PEMBELIAN)
VALUES ('B005', 'Kipas Angin', 10 , 9);
UPDATE DETIL_PEMBELIAN SET JUMLAH_PEMBELIAN = 0 WHERE JUMLAH_PEMBELIAN = NULL;
DELETE FROM DETIL_PEMBELIAN;



--1. Gunakan user / database pembelian yang telah dibuat pada latihan sebelumnya, kemudian tambahkan sebuah table KARYAWAN
CREATE TABLE KARYAWAN (
NIK VARCHAR2(20) PRIMARY KEY,
Nama VARCHAR2(20),
Alamat VARCHAR2(20)
);

INSERT INTO KARYAWAN
VALUES ('K001', 'Wawan', 'Plaju');
INSERT INTO KARYAWAN
VALUES ('K002', 'Badu', 'Perumnas');

--2
INSERT INTO KARYAWAN VALUES ('K003', 'Cici', 'Perumnas');
UPDATE KARYAWAN SET alamat = 'bukit besar' WHERE NIK = 'K003';
COMMIT;
SELECT * FROM KARYAWAN ; 

--5
DELETE FROM KARYAWAN ;
ROLLBACK;
SELECT * FROM KARYAWAN;
DELETE FROM KARYAWAN WHERE NIK = 'K002' ;
SELECT * FROM KARYAWAN;
COMMIT;


--7
INSERT INTO KARYAWAN VALUES ('K004', 'Nino', 'Rembang');
SAVEPOINT PERUBAHAN1;

INSERT INTO KARYAWAN VALUES ('K005', 'Hamdan', 'Depok');
SAVEPOINT PERUBAHAN2;

UPDATE KARYAWAN SET ALAMAT = 'Solo' WHERE NIK = 'K005';
SAVEPOINT PERUBAHAN3;

INSERT INTO KARYAWAN VALUES ('K006', 'Gattha', 'Depok');
SAVEPOINT PERUBAHAN4;

SELECT * FROM KARYAWAN;

ROLLBACK TO PERUBAHAN3;
ROLLBACK TO PERUBAHAN2;
ROLLBACK TO PERUBAHAN1;
ROLLBACK;